//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageId, True, UntilDate};

impl_payload! {
    /// Use this method to approve a suggested post in a direct messages chat. The bot must have the _can_post_messages_ administrator right in the corresponding channel chat. Returns _True_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub ApproveSuggestedPost (ApproveSuggestedPostSetters) => True {
        required {
            /// Unique identifier for the target direct messages chat
            pub chat_id: ChatId [into],
            /// Identifier of a suggested post message to approve
            #[serde(flatten)]
            pub message_id: MessageId,
        }
        optional {
            /// Point in time (Unix timestamp) when the post is expected to be published; omit if the date has already been specified when the suggested post was created. If specified, then the date must be not more than 2678400 seconds (30 days) in the future
            pub send_date: UntilDate,
        }
    }
}
