//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{BusinessConnectionId, ChatId, Seconds, Story, StoryId};

impl_payload! {
    /// Reposts a story on behalf of a business account from another business account. Both business accounts must be managed by the same bot, and the story on the source account must have been posted (or reposted) by the bot. Requires the _can_manage_stories_ business bot right for both business accounts. Returns [`Story`] on success.
    ///
    /// [`Story`]: crate::types::Story
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub RepostStory (RepostStorySetters) => Story {
        required {
            /// Unique identifier of the business connection
            pub business_connection_id: BusinessConnectionId,
            /// Unique identifier of the chat which posted the story that should be reposted
            pub from_chat_id: ChatId [into],
            /// Unique identifier of the story that should be reposted
            pub from_story_id: StoryId,
            /// Period after which the story is moved to the archive, in seconds; must be one of `6 * 3600`, `12 * 3600`, `86400`, or `2 * 86400`
            pub active_period: Seconds,
        }
        optional {
            /// Pass _true_ to keep the story accessible after it expires
            pub post_to_chat_page: bool,
            /// Pass _true_ if the content of the story must be protected from forwarding and screenshotting
            pub protect_content: bool,
        }
    }
}
