//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageEntity, ParseMode, ThreadId, True};

impl_payload! {
    /// Use this method to stream a partial message to a user while the message is being generated; supported only for bots with forum topic mode enabled. Returns _true_ on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: ChatId [into],
            /// Unique identifier of the message draft; must be non-zero. Changes of drafts with the same identifier are animated
            pub draft_id: u32,
            /// Text of the message to be sent, 1-4096 characters after entities parsing
            pub text: String [into],
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Mode for parsing entities in the message text. See [formatting options] for more details.
            ///
            /// [formatting options]: https://core.telegram.org/bots/api#formatting-options
            pub parse_mode: ParseMode,
            /// List of special entities that appear in message text, which can be specified instead of _parse_mode_
            pub entities: Vec<MessageEntity> [collect],
        }
    }
}
